spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
  main:
    allow-circular-references: true

